name: Python Telegram Bot CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Install dependencies using PDM
      run: |
        pdm lock --update-reuse
        pdm sync

    - name: Run tests
      run: |
        echo "Running tests..."
        # Здесь добавьте команды для запуска ваших тестов



    - name: Build Podman image
      run: |
        podman build -t drozdovnikolai/telegram-bot:${{ github.sha }} .
        podman tag drozdovnikolai/telegram-bot:${{ github.sha }} myusername/telegram-bot:latest

    - name: Push Podman image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | podman login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        podman push drozdovnikolai/telegram-bot:${{ github.sha }}
        podman push drozdovnikolai/telegram-bot:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        podman pull myusername/telegram-bot:latest
        podman stop telegram_bot || true
        podman rm telegram_bot || true
        podman run -d --name telegram_bot --network="host" -p 5000:5000 myusername/telegram-bot:latest
        EOF
